
[general]
	test = true

	[general.custom_chat]
		chat_channel = 0
		custom_message = "test"

	[general.hud]
		legion_counter = true

	[general.notifications]
		autopet_display = true

[dungeons]

	[dungeons.crypt_reminder]
		crypt_reminder = true
		reminder_interval = 60
		missing_crypts_title = true
		announce_crypts = true

	[dungeons.leap]
		leap_announce = true
		hide_leap_messages = 0

	[dungeons.mimic]
		send_mimic_dead_message = true
		hightlight_mimic_chest = true

	[dungeons.misc]
		bat_dead_title = true

[dungeon]

	[dungeon.mimic]
		send_mimic_dead_message = false

["f7/m7"]

	["f7/m7".p3]
		terminal_class_label = true

