
[chatcommand]
	enable_chat_commands = true
	chat_commands_prefix = "!"

	[chatcommand.blacklist]
		enable_blacklist = false
		blacklist = ""

	[chatcommand.whitelist]
		enable_whitelist = false
		whitelist = ""

